name: MLOps

on:
  # Runs on pushes targeting main branch
  push:
    branches:
      - main
      - mlops # TODO remove this, only for testing purposes

  # Runs on pull requests
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  train-and-report:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - name: Install Tesseract
        run: sudo apt install tesseract-ocr
      - name: Install dependencies
        run: pip install --requirement requirements-freeze.txt
      - name: Train model
        run: dvc repro --pull
      - name: Setup CML
        uses: iterative/setup-cml@v2
        with:
          version: '0.20.6'
      - name: Create CML report
        run: |
          # Add title to the report
          echo "# Experiment Report (${{ github.sha }})" >> report.md

          echo "## Metrics workflow" >> report.md
          dvc metrics --md >> report.md

          # Create plots
          echo "## Plots" >> report.md

          # Create confusion matrix
          echo "### Confusion Matrix" >> report.md
          echo '![](./dvc_plots/static/workspace_evaluation_orientation_confusion_matrix.png "Confusion Matrix")' >> report.md

          # Publish the CML report
          cml comment update --target=pr --publish report.md
