name: MLOps

on:
  # Runs on pushes targeting main branch
  push:
    branches:
      - main
      - mlops # TODO remove this, only for testing purposes

  # Runs on pull requests
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - name: Install Tesseract
        run: sudo apt install tesseract-ocr
      - name: Install dependencies
        run: pip install --requirement requirements-freeze.txt
      - name: Train model
        run: dvc repro --pull

